name: appcenter_sdk
description: Development plugin for the App Center Analytics, Crashes & Distribution for Flutter
version: 1.0.0
repository: https://github.com/zoocityboy/appcenter_sdk
publish_to: https://gitea.prntes.space/api/packages/platform/pub/

environment:
  sdk: ^3.1.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  pigeon: ^10.1.6
  zoo_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: zoo.cityboy.appcenter_sdk
        pluginClass: AppcenterSdkPlugin
      ios:
        pluginClass: AppcenterSdkPlugin
