name: appcenter
description: Development plugin for the App Center Analytics and Crashes for Flutter
version: 0.5.1
repository: https://github.com/zoocityboy/appcenter

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  pigeon: ^10.1.6
  zoo_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: zoo.cityboy.appcenter
        pluginClass: AppCenterPlugin
      ios:
        pluginClass: AppCenterPlugin
